version: '3'

services: 
  app:
    build: .
      context: .
      dockerfile: Dockerfile.prod
    container_name: app
    # entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh 
    # environment: 
    #   - DB_HOST=db
    #   - DB_DATABASE=laravel
    #   - DB_USERNAME=root
    #   - DB_PASSWORD=root
    volumes: 
      - .:/var/www
    networks: 
      - work_app  
    depends_on: 
      - db
      - redis  

  db:
    container_name: db
    build: ./.docker/mysql
    command: --innodb-use-native-aio=0
    restart: always
    tty: true 
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_DB_HOST=db
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - work_app          
    volumes: 
      - ./.docker/mysql/dbdados:/var/lib/mysql  
        
  nginx:
    build: ./.docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports: 
      - "8000:80"
    volumes: 
      - .:/var/www
    networks: 
      - work_app   
    depends_on: 
      - app  
       
  redis:
    image: redis:alpine
    expose:
      - 6379
    networks: 
      - work_app        

networks: 
  work_app:
    driver: bridge      


